version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/usr/share/elasticsearch/data
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

#   kibana:
#     image: docker.elastic.co/kibana/kibana:8.4.0
#     ports:
#       - "5601:5601"
# #    environment:
# #      - ELASTICSEARCH_PASSWORD=${ES_PASS}
#     configs:
#       - source: kibana_config
#         target: /usr/share/config/kibana.yml
#     extra_hosts:
#       - "host.docker.internal:172.17.0.1"

# configs:
#   elastic_config:
#     file: ./config/elasticsearch.yml
  # kibana_config:
  #   file: ./config/kibana.yml
