version: '3.6'

services:
  db:
    build: .
    container_name: postgres
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:172.17.0.1"